version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: atem
      POSTGRES_PASSWORD: osiris
      POSTGRES_DB: ygo_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atem -d ygo_app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    expose:
        - 5432
    networks:
      - exodia-net

  api:
    image: exodialib-core:latest
    ports:
      - "9001:9001"
    expose:
        - 9001
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - exodia-net

networks:
  exodia-net:
    driver: bridge